school/grades/urls.py
from django.urls import path

from grades import views

app_name = 'grades'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('success/', views.success, name='success'),
    path('reports/', views.reports, name='reports'),
    path(
        'student-detail/<int:student_id>',
        views.student_detail,
        name='student_detail'
    ),
    path(
        'student',
        views.student_delete,
        name='student_delete'
    )
]

school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grades/', include('grades.urls'))
]

school/grades/models.py
from django.db import models


class Student(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        db_table = 'students'

    def media(self):
        notas = self.grade_set.all()
        nota1 = notas[0].value
        nota2 = notas[1].value
        nota3 = notas[2].value

        media = (nota1 + nota2 + nota3) / len(notas)
        return float("{:.1f}".format(media))


class Grade(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    value = models.FloatField()

    class Meta:
        db_table = 'grades'

school/grades/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from grades.models import Student


def index(request):
    return render(request, 'grades/index.html')


def register(request):
    name = request.POST['name']
    student = Student(name=name)
    student.save()

    grade1 = float(request.POST['grade1'])
    grade2 = float(request.POST.get('grade2'))
    grade3 = float(request.POST['grade3'])

    student.grade_set.create(value=grade1)
    student.grade_set.create(value=grade2)
    student.grade_set.create(value=grade3)

    return HttpResponseRedirect(reverse('grades:success'))


def success(request):
    return render(request, 'grades/success.html')


def reports(request):
    students = Student.objects.all()

    return render(
        request,
        'grades/reports.html',
        {'students_list': students}
    )


def student_detail(request, student_id):
    student = Student.objects.get(pk=student_id)

    return render(
        request,
        'grades/student_detail.html',
        {'student': student}
    )


def student_delete(request):
    student_id = request.POST.get('student_id')
    student = Student.objects.get(pk=student_id)
    student.delete()

    return render(request, 'grades/student_deleted.html')

school/grades/templates/grades/index.html
<h1>Cadastro de alunos e notas</h1>
<hr>

<form action="{% url 'grades:register' %}" method="POST">
    {% csrf_token %}
    <div>
        <label for="name">Nome do aluno: </label>
        <input type="text" name="name" id="name">
    </div>

    <div>
        <label for="grade1">Primeira nota: </label>
        <input type="text" name="grade1" id="grade1">
    </div>

    <div>
        <label for="grade2">Segunda nota: </label>
        <input type="text" name="grade2" id="grade2">
    </div>

    <div>
        <label for="grade3">Terceira nota: </label>
        <input type="text" name="grade3" id="grade3">
    </div>

    <div><input type="submit" value="Enviar"></div>
</form>

school/grades/templates/grades/reports.html
<h1>Resultados</h1>


{% for student in students_list %}
<div>
    <p>Aluno: <a href="{% url 'grades:student_detail' student.id %}">{{ student.name }}</a></p>
    <strong>{% if student.media > 7 %}{{ student.name}} foi aprovado. {% else %}{{ student.name }} foi reprovado.{% endif %}</strong>
</div>
<hr>
{% endfor %}

<a href="{% url 'grades:index' %}">Voltar para a página inicial</a>

school/grades/templates/grades/student_deleted.html
<h1>Aluno excluído com sucesso</h1>

<a href="{% url 'grades:index' %}">Voltar para a página inicial</a>
<a href="{% url 'grades:reports' %}">Ver relatório</a>

school/grades/templates/grades/student_detail.html
<h1>Notas do aluno {{ student.name }}</h1>

<div>
    {% for grade in student.grade_set.all %}
        <p>Nota {{ forloop.counter }}: {{ grade.value }}</p>
    {% endfor %}
    <p>Média final: {{ student.media }}</p>
</div>

<a href="{% url 'grades:index' %}">Voltar para a página inicial</a>

<form action="{% url 'grades:student_delete'%}" method="POST">
    {% csrf_token %}
    <input type="hidden" value="{{ student.id }}" name="student_id">
    <input type="submit" Value="Apagar aluno">
</form>

school/grades/templates/grades/success.html
<h1>Notas cadastradas com sucesso.</h1>


<a href="{% url 'grades:index' %}">Voltar a página inicial</a>
<a href="{% url 'grades:reports' %}">Ver relatório</a>